services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL=postgresql://rada_user:rada_password@db:5432/rada_islami_db?schema=public
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000/api/v1
    depends_on:
      - backend

  db:
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=rada_user
      - POSTGRES_PASSWORD=rada_password
      - POSTGRES_DB=rada_islami_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
